In [1]:
import numpy as np
from numpy.ma.core import swapaxes, concatenate

In [4]:
a= np.zeros((3,3)) # a matrix full of zeros 3,3

In [5]:
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:
b=np.ones((4,4)) # a matrix full of ones
b

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
c=np.full((4,4),6) # a matrix full of 6
c

array([[6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6]])

In [10]:
import time

In [15]:
start=time.time()
l=[]
for i in range(10):
    ops=i*100
    l.append(ops)
print(l)
end=time.time()

print("Time taken to perform the operation over list :" ,end-start)

[0, 100, 200, 300, 400, 500, 600, 700, 800, 900]
Time taken to perform the operation over list : 0.0009429454803466797


In [18]:
# lets perform the same opeartion over array
start2=time.time()
ary=np.arange(10)
for i in ary:
    oper= ary*100

print(oper)
end2=time.time()
print("Time taken to perform the operation over array :" ,end2-start2)

[  0 100 200 300 400 500 600 700 800 900]
Time taken to perform the operation over array : 0.004395008087158203


In [19]:
import sys

In [20]:
print(sys.getsizeof(oper)
,sys.getsizeof(l))

192 184


In [21]:
array=np.arange(10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
array+12

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

In [31]:
# dimension and shape of array
"""
a single no like 32 - scalar dimension is 0
a vector like 10,20,30 - vector - dimension is 1
 matrix -
as no of brackets will increase the dimension of array

"""

zero_d= np.array(34)
zero_d.ndim

one_d=np.array([1,2,3,4,5])
one_d.ndim

two_d=np.array([[1,2,3],[4,5,6]])
two_d.ndim
print(f"dimension of {zero_d.ndim}, {one_d.ndim}, {two_d.ndim}")


dimension of 0, 1, 2


In [40]:
print(np.array([[[

]]]).ndim)


"""
number of brackets will increase the dimension of array
"""

3


'\nnumber of brackets will increase the dimension of array\n'

In [42]:
# Creation of array

array1= np.arange(1,100)
array1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [43]:
# with skip nature
array_2=np.arange(1,100,5)
array_2

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

In [44]:
# with linearly space between two number

# linspace(start,stop,no_of_elements)

array_3= np.linspace(1,10,5)
array_3

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [46]:
array_4=np.logspace(1,4,4)
array_4
"""
logspace(start,stop,no_of_elements)
logspace result is in log scale like 10 **1 ,10**2,10**3
"""

array([   10.,   100.,  1000., 10000.])

In [50]:
# creating an uninitialized  and empty array
array_5= np.empty([3,3])
array_5

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [48]:
print(array_5.shape,array_5.size,array_5.ndim)

(3, 3) 9 2


In [51]:
"""
uninitialized array meanse it is not filled with any value
empty array means it is filled with some value
"""
Print("--------------- Important--------")

"""
NumPy me uninitialized ya empty array (jo np.empty() se banta hai) basically ek aisa array hota hai jisme memory to reserve ho jaati hai, lekin uske andar koi value set nahi hoti. Matlab NumPy bas RAM ka ek block le leta hai aur jo bhi purana data (garbage values) us memory me pada hota hai, wahi dikha deta hai. Ye numbers random lagte hain, par asal me wo sirf pehle ke memory bits hote hain. Isliye har run me output thoda alag bhi ho sakta hai, ye depend karta hai ki OS kis memory area ko allocate karta hai. np.zeros() ke opposite, jo har element ko 0 se initialize karta hai, np.empty() fast hota hai — par use tabhi karo jab tum us array ke andar ki values turant overwrite karne wale ho.
"""




'\nuninitialized array meanse it is not filled with any value\nempty array means it is filled with some value\n'

In [59]:
 """random.rand - generates values between  0 and 1 having random distribution means mean = 0.5 and variance = .29

"""
array_6=np.random.rand(20)
array_6

array([0.2822054 , 0.56477085, 0.65840393, 0.84542289, 0.55754307,
       0.61027645, 0.63310418, 0.33240126, 0.78411874, 0.84185981,
       0.52774463, 0.93379954, 0.60237088, 0.56631792, 0.05947135,
       0.23510363, 0.85045302, 0.59334062, 0.01536397, 0.44091738])

In [61]:
array_6.reshape([5,4])

array([[0.2822054 , 0.56477085, 0.65840393, 0.84542289],
       [0.55754307, 0.61027645, 0.63310418, 0.33240126],
       [0.78411874, 0.84185981, 0.52774463, 0.93379954],
       [0.60237088, 0.56631792, 0.05947135, 0.23510363],
       [0.85045302, 0.59334062, 0.01536397, 0.44091738]])

In [63]:
array_7=np.random.randn(3,4)
array_7
"""
with randn we get values between -1 and 1 having mean = 0 and variance = 1
"""

array([[ 1.30171253, -1.03252987, -0.47423919, -1.01059194],
       [-0.46753705, -0.02279947, -1.13053479,  0.64141168],
       [-0.32034089,  0.39152868, -1.41578561,  0.49118031]])

In [68]:
array_8=np.random.randint(10,20,[3,3])
array_8

"""
randint - generates random integer between 10 and 20
"""


'\nrandint - generates random integer between 10 and 20\n'

In [70]:
# Numpy Data Type and typecasting

"""
int
bool
stringe
float
complex
"""

'\nint\nbool\nstringe\nfloat\ncomplex \n'

In [ ]:
# typecasting conversion of data type one into another
# by using astype()


In [73]:
# Reshaping, -------- Reshape, Ravel, flatten
"""
ravel is to convert N-D array into 1D array - but returns a view
flatten is to convert N-D array into 1D array - but returns a copy


flatten() → ek nayi copy banayi → flatten ke result me change kia to v original safe rhega.
ravel() → view (reference) return kiya → ravel ke result me change kia to original v chud jaiga

"""




8

In [78]:
# rehape testing
at=np.random.randint(1,10,[5,5])
at
at.flatten()
at.ravel()

array([1, 9, 9, 5, 6, 4, 1, 3, 6, 2, 4, 3, 6, 8, 9, 4, 3, 2, 5, 7, 6, 5,
       1, 6, 9])

In [126]:
# indexing and sliciing

atr=np.arange(1,20)
print(atr)

print(atr[1:10:2])
print("reverse indexing",atr[-1:10:-1])


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 2  4  6  8 10]
reverse indexing [19 18 17 16 15 14 13 12]


In [127]:
# indexing and slicing of multi dimension array(matrix)

atr=np.random.randint(10,20,[6,6])
print(atr)

# lets access first row
print("first row",atr[0])
print("first column",atr[:,0])
print("third row and second column ",atr[3,2])
print("lets create a sub matrix", atr[1:3,1:3])

[[13 14 14 14 12 13]
 [14 14 12 19 18 15]
 [17 14 15 13 10 14]
 [13 15 15 15 11 17]
 [14 11 19 15 14 12]
 [17 11 15 19 13 12]]
first row [13 14 14 14 12 13]
first column [13 14 17 13 14 17]
third row and second column  15
lets create a sub matrix [[14 12]
 [14 15]]


In [128]:
# let try looping over iterator
atr
l=[]
for i in np.nditer(atr):
    l.append(i+10)

print(l)

[np.int64(23), np.int64(24), np.int64(24), np.int64(24), np.int64(22), np.int64(23), np.int64(24), np.int64(24), np.int64(22), np.int64(29), np.int64(28), np.int64(25), np.int64(27), np.int64(24), np.int64(25), np.int64(23), np.int64(20), np.int64(24), np.int64(23), np.int64(25), np.int64(25), np.int64(25), np.int64(21), np.int64(27), np.int64(24), np.int64(21), np.int64(29), np.int64(25), np.int64(24), np.int64(22), np.int64(27), np.int64(21), np.int64(25), np.int64(29), np.int64(23), np.int64(22)]


In [129]:
# ndenumerate  used to get the value and the index

for index,value in np.ndenumerate(atr):
    print(index,value,end=" ")

(0, 0) 13 (0, 1) 14 (0, 2) 14 (0, 3) 14 (0, 4) 12 (0, 5) 13 (1, 0) 14 (1, 1) 14 (1, 2) 12 (1, 3) 19 (1, 4) 18 (1, 5) 15 (2, 0) 17 (2, 1) 14 (2, 2) 15 (2, 3) 13 (2, 4) 10 (2, 5) 14 (3, 0) 13 (3, 1) 15 (3, 2) 15 (3, 3) 15 (3, 4) 11 (3, 5) 17 (4, 0) 14 (4, 1) 11 (4, 2) 19 (4, 3) 15 (4, 4) 14 (4, 5) 12 (5, 0) 17 (5, 1) 11 (5, 2) 15 (5, 3) 19 (5, 4) 13 (5, 5) 12 

In [130]:
## view and copy

"""
so in case of view if you make any changess in view it will reflect in original array

while in case of copy if you make any changess in copy it will not reflect in original array
"""

print(atr[1,1])
view=atr
view[1,1]= 99 # because we are making change in view it will reflect in original array
print(atr[1,1],view[1,1])

# while
copy=atr.copy()
copy[2,2]= 89 # because we are making change in copy it will not reflect in original array
atr[2,2]
print(atr[2,2],copy[2,2])

14
99 99
15 89


In [131]:
# transpose - row becomes column and column becomes row
satr=atr[0:3,0:3]
print(satr,
      satr.transpose())

[[13 14 14]
 [14 99 12]
 [17 14 15]] [[13 14 17]
 [14 99 14]
 [14 12 15]]


In [132]:
# swap axis

s_atr=atr[:2,:2]
s_atr
print(s_atr, np.swapaxes(s_atr,0,1))

[[13 14]
 [14 99]] [[13 14]
 [14 99]]


In [133]:
# interchanging two row  Similary column can be interchanged
atr[:1,:]
atr.shape
atr[5,:]

print(f" first row {atr[:1,:]}",
      f"last rpw {atr[5:,:]}")
# now interchange them

atr[:1,:] = atr[5,:]
print(atr[:1,:],atr[5,:])

 first row [[13 14 14 14 12 13]] last rpw [[17 11 15 19 13 12]]
[[17 11 15 19 13 12]] [17 11 15 19 13 12]


In [146]:

# concatination - combinig two array togeather
"""
concate only works with scalar
to concat matrix use vstack and hstack
 v stack - row wise concatination - increases no of rows / ek ke niche dusra
 h stack - column wise concatination - increases no of column / side by side

"""


print(satr,
satr.transpose())
print(f" vertical stack {np.vstack((satr, satr.transpose()))}")
print(f"horizontal stacking {np.hstack((satr,satr.transpose())) }")


[[17 11 15]
 [14 99 12]
 [17 14 15]] [[17 14 17]
 [11 99 14]
 [15 12 15]]
 vertical stack [[17 11 15]
 [14 99 12]
 [17 14 15]
 [17 14 17]
 [11 99 14]
 [15 12 15]]
horizontal stacking [[17 11 15 17 14 17]
 [14 99 12 11 99 14]
 [17 14 15 15 12 15]]


In [147]:
# split can be vertical as well as can be horizontal
"""
spliting can be achived by 3 way

with function split - split(array, axis=0/1, no_of_parts))
with hsplit- hsplit(array, no_of_parts)
with vsplit- vsplit(array, no_of_parts)
"""

In [159]:
atr
print(f"Over axis-0,{np.split(atr,6,axis=0)}",
      f" Over axis-1,{np.split(atr,6,axis=1)}")

Over axis-0,[array([[17, 11, 15, 19, 13, 12]]), array([[14, 99, 12, 19, 18, 15]]), array([[17, 14, 15, 13, 10, 14]]), array([[13, 15, 15, 15, 11, 17]]), array([[14, 11, 19, 15, 14, 12]]), array([[17, 11, 15, 19, 13, 12]])]  Over axis-1,[array([[17],
       [14],
       [17],
       [13],
       [14],
       [17]]), array([[11],
       [99],
       [14],
       [15],
       [11],
       [11]]), array([[15],
       [12],
       [15],
       [15],
       [19],
       [15]]), array([[19],
       [19],
       [13],
       [15],
       [15],
       [19]]), array([[13],
       [18],
       [10],
       [11],
       [14],
       [13]]), array([[12],
       [15],
       [14],
       [17],
       [12],
       [12]])]


In [162]:
np.repeat(atr,3,axis=1)

# repeat - repeats the value either in axis=0 or axis = 1

array([[17, 17, 17, 11, 11, 11, 15, 15, 15, 19, 19, 19, 13, 13, 13, 12,
        12, 12],
       [14, 14, 14, 99, 99, 99, 12, 12, 12, 19, 19, 19, 18, 18, 18, 15,
        15, 15],
       [17, 17, 17, 14, 14, 14, 15, 15, 15, 13, 13, 13, 10, 10, 10, 14,
        14, 14],
       [13, 13, 13, 15, 15, 15, 15, 15, 15, 15, 15, 15, 11, 11, 11, 17,
        17, 17],
       [14, 14, 14, 11, 11, 11, 19, 19, 19, 15, 15, 15, 14, 14, 14, 12,
        12, 12],
       [17, 17, 17, 11, 11, 11, 15, 15, 15, 19, 19, 19, 13, 13, 13, 12,
        12, 12]])

In [166]:
np.tile(atr,2) # repeat the whole row

array([[17, 11, 15, 19, 13, 12, 17, 11, 15, 19, 13, 12],
       [14, 99, 12, 19, 18, 15, 14, 99, 12, 19, 18, 15],
       [17, 14, 15, 13, 10, 14, 17, 14, 15, 13, 10, 14],
       [13, 15, 15, 15, 11, 17, 13, 15, 15, 15, 11, 17],
       [14, 11, 19, 15, 14, 12, 14, 11, 19, 15, 14, 12],
       [17, 11, 15, 19, 13, 12, 17, 11, 15, 19, 13, 12]])

In [168]:
"""
Condition based operations
where(condition, value_if_true, value_if_false)
"""

atr

np.where(atr>15, "High", "Low")

array([['High', 'Low', 'Low', 'High', 'Low', 'Low'],
       ['Low', 'High', 'Low', 'High', 'High', 'Low'],
       ['High', 'Low', 'Low', 'Low', 'Low', 'Low'],
       ['Low', 'Low', 'Low', 'Low', 'Low', 'High'],
       ['Low', 'Low', 'High', 'Low', 'Low', 'Low'],
       ['High', 'Low', 'Low', 'High', 'Low', 'Low']], dtype='<U4')

In [171]:
np.argwhere(atr>15)

array([[0, 0],
       [0, 3],
       [1, 1],
       [1, 3],
       [1, 4],
       [2, 0],
       [3, 5],
       [4, 2],
       [5, 0],
       [5, 3]])

In [172]:
np.logical_and(atr>15, atr<18 )

array([[ True, False, False, False, False, False],
       [False, False, False, False, False, False],
       [ True, False, False, False, False, False],
       [False, False, False, False, False,  True],
       [False, False, False, False, False, False],
       [ True, False, False, False, False, False]])

In [173]:
np.nonzero(atr)

(array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3,
        3, 3, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5]),
 array([0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3,
        4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5]))

In [174]:
atr

array([[17, 11, 15, 19, 13, 12],
       [14, 99, 12, 19, 18, 15],
       [17, 14, 15, 13, 10, 14],
       [13, 15, 15, 15, 11, 17],
       [14, 11, 19, 15, 14, 12],
       [17, 11, 15, 19, 13, 12]])

In [175]:
# Broadcasting
"""
broadcasting is case of matrix opetation, to strech the shorter matrix to match the size of longer matrix
 to perform the operation we need to make sure that the dimensions of two matrix are same
 or one of the dimension can be 1   """


In [181]:
a=np.random.randint(10,20,[3,1])
b=np.random.randint(10,20,[1,3])

print(f"a;{a} \nb;{b} \n a+b;{a+b}")

a;[[12]
 [18]
 [11]] 
b;[[15 19 19]] 
 a+b;[[27 31 31]
 [33 37 37]
 [26 30 30]]


In [182]:
# Vectorization
"""
vectorization is the process of converting a function into a vectorized function
"""
"""
to implement the function over a matrix we need to use vectorize

"""
def square(x):
    return x**2

# to vectorize
v_square=np.vectorize(square)

# to check its effect

print(f"atr= {atr} \n v_atr= {v_square(atr)}")


atr= [[17 11 15 19 13 12]
 [14 99 12 19 18 15]
 [17 14 15 13 10 14]
 [13 15 15 15 11 17]
 [14 11 19 15 14 12]
 [17 11 15 19 13 12]] 
 v_atr= [[ 289  121  225  361  169  144]
 [ 196 9801  144  361  324  225]
 [ 289  196  225  169  100  196]
 [ 169  225  225  225  121  289]
 [ 196  121  361  225  196  144]
 [ 289  121  225  361  169  144]]
